export type APP_START_KICKED = 'APP_START_KICKED';
export const APP_START_KICKED: APP_START_KICKED = 'APP_START_KICKED';

export type APP_STARTED = 'APP_STARTED';
export const APP_STARTED: APP_STARTED = 'APP_STARTED';

export type APP_START_FAILED = 'APP_START_FAILED';
export const APP_START_FAILED: APP_START_FAILED = 'APP_START_FAILED';
